### ISSUE TITLE
Austral code

### ISSUE THREAD

**Issue by Inaksa** [JamesSedlacek/CurrencyProviding#1]
Hi, there is an error in your screenshots. You state that ARS is the Austral, but the ISO code for Austral is ARA.
ARS is the currency we have Argentinian Peso, Austral was removed from circulation in 1990 or 1991.

**Comment by JamesSedlacek** [comment]
Good catch! Feel free to open a PR to fix this.

**Comment by Inaksa** [comment]
Done.
